# Generated by Django 4.2.3 on 2023-08-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='caption',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
