# Generated by Django 4.2.3 on 2023-08-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_users_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='poster_waiter',
            field=models.BooleanField(default=True),
        ),
    ]
