# Generated by Django 4.2.3 on 2023-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_users_poster_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='poster_waiter',
            field=models.BooleanField(default=False),
        ),
    ]
