# Generated by Django 4.2.3 on 2023-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_users_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('case_type', models.CharField(choices=[('co_performer', '共演している'), ('accidentally_in_video', '映り込んでいる'), ('copyright_infringement', '自身の著作物が映っている'), ('others', 'その他')], max_length=50, verbose_name='ケースの種類')),
                ('username', models.CharField(max_length=255, verbose_name='投稿者のユーザーネーム')),
                ('post_title', models.CharField(max_length=255, verbose_name='投稿のタイトル')),
                ('details', models.TextField(verbose_name='詳細')),
            ],
        ),
    ]
