# Generated by Django 4.2.3 on 2023-08-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_deleterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deleterequest',
            old_name='username',
            new_name='postername',
        ),
    ]
