# Generated by Django 4.2.3 on 2023-08-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_username_deleterequest_postername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='case_type',
            field=models.CharField(choices=[('co_performer', '自身が共演している'), ('accidentally_in_video', '自身が映り込んでいる'), ('copyright_infringement', '自身の著作物が映っている'), ('others', 'その他')], max_length=50, verbose_name='ケースの種類'),
        ),
    ]
