# Generated by Django 4.2.3 on 2023-09-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_users_is_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rating',
            field=models.FloatField(blank=True, choices=[(3.0, '3'), (2.5, '2.5'), (2.0, '2')], default=2.5, null=True),
        ),
    ]
