# Generated by Django 4.2.3 on 2023-09-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_users_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='rating',
            new_name='dimension',
        ),
    ]
