# Generated by Django 4.2.3 on 2023-09-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_rating_users_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='boost_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('boost', 'Boost'), ('superboost', 'Super Boost'), ('viewyboost', 'Viewy Boost')], default='normal', max_length=10),
        ),
    ]
