# Generated by Django 4.2.3 on 2023-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_users_boost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=6, null=True),
        ),
    ]
