# Generated by Django 4.2.3 on 2023-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_surveys_surveyresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='name_ja',
            field=models.CharField(max_length=50, null=True, verbose_name='日本語名'),
        ),
    ]
