# Generated by Django 4.2.3 on 2023-09-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_features_name_ja'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_by_affiliateadvertiser',
            field=models.BooleanField(default=False),
        ),
    ]
