# Generated by Django 4.2.3 on 2023-09-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_users_is_by_affiliateadvertiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_by_affiliateadvertiser',
        ),
    ]
