# Generated by Django 4.2.3 on 2023-09-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_users_is_by_affiliateadvertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_affiliateadvertiser',
            field=models.BooleanField(default=False),
        ),
    ]
