# Generated by Django 4.2.3 on 2023-09-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_users_is_affiliateadvertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_specialadvertiser',
            field=models.BooleanField(default=False),
        ),
    ]
