# Generated by Django 4.2.3 on 2023-10-11 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_users_support_follow_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_url', models.URLField()),
                ('approve', models.BooleanField(default=False)),
                ('poster', models.ManyToManyField(related_name='ice_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('img', models.ImageField(upload_to='notifications/images/')),
                ('video', models.FileField(upload_to='notifications/videos/')),
                ('content2', models.TextField()),
                ('only_partner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='accounts.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification')},
            },
        ),
        migrations.CreateModel(
            name='FreezeNotificationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('freeze_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='accounts.freezenotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_notification_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'freeze_notification')},
            },
        ),
    ]
