# Generated by Django 4.2.3 on 2023-10-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_freezenotification_notification_notificationview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='notifications_images/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='only_partner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='notifications_videos/'),
        ),
    ]
