# Generated by Django 4.2.3 on 2023-10-11 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_freezenotification_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezenotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
