# Generated by Django 4.2.3 on 2023-10-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_freezenotification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='boost_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('firstboost', 'FIRST BOOST'), ('boost', 'Boost'), ('superboost', 'Super Boost'), ('viewyboost', 'Viewy Boost')], default='normal', max_length=10),
        ),
    ]
