# Generated by Django 4.2.3 on 2023-10-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_users_boost_type'),
        ('accounts', '0033_blocks'),
    ]

    operations = [
    ]
