# Generated by Django 4.2.3 on 2023-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_merge_0033_alter_users_boost_type_0033_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birth_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
