# Generated by Django 4.2.3 on 2023-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_users_birth_month_users_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='max_ad_per',
            field=models.FloatField(default=0.2),
        ),
    ]
