# Generated by Django 4.2.3 on 2023-11-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_users_max_ad_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='max_ad_per',
            field=models.FloatField(default=0.25),
        ),
    ]
