# Generated by Django 4.2.3 on 2023-11-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_users_max_ad_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='max_ad_per',
        ),
        migrations.AddField(
            model_name='users',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
