# Generated by Django 4.2.3 on 2023-07-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
                ('ad_tag', models.TextField()),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
