# Generated by Django 4.2.3 on 2023-07-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='caption',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ad',
            name='hashtag1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ad',
            name='hashtag2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ad',
            name='hashtag3',
            field=models.CharField(default='', max_length=30),
        ),
    ]
