# Generated by Django 4.2.3 on 2023-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_ad_caption_ad_hashtag1_ad_hashtag2_ad_hashtag3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
