# Generated by Django 4.2.3 on 2023-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_ad_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotHashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag1', models.CharField(blank=True, max_length=50)),
                ('hashtag2', models.CharField(blank=True, max_length=50)),
                ('hashtag3', models.CharField(blank=True, max_length=50)),
                ('hashtag4', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hothashtags',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('underage', '未成年者が出演している'), ('insufficient_mosaic', 'モザイク処理が十分でない'), ('violent', '暴力的な内容'), ('inappropriate', '不適切な内容'), ('other', 'その他')], max_length=20),
        ),
    ]
