# Generated by Django 4.2.3 on 2023-08-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_hothashtags_posts_views_count_alter_report_reason'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hothashtags',
            table='hothashtags',
        ),
    ]
