# Generated by Django 4.2.3 on 2023-08-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_hothashtags_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotHashtags',
        ),
    ]
