# Generated by Django 4.2.3 on 2023-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_delete_hothashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotHashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag1', models.CharField(blank=True, max_length=50)),
                ('hashtag2', models.CharField(blank=True, max_length=50)),
                ('hashtag3', models.CharField(blank=True, max_length=50)),
                ('hashtag4', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hothashtags',
            },
        ),
    ]
