# Generated by Django 4.2.3 on 2023-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_hothashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='favorite_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
