# Generated by Django 4.2.3 on 2023-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_posts_favorite_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ads',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
