# Generated by Django 4.2.3 on 2023-08-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_ads_click_count_ads_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='click_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
