# Generated by Django 4.2.3 on 2023-08-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_ads_click_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ads',
            name='hashtag1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='hashtag2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='hashtag3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hashtag1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hashtag2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hashtag3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.URLField(max_length=80, null=True),
        ),
    ]
