# Generated by Django 4.2.3 on 2023-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_ads_caption_alter_ads_hashtag1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiHiraganaSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=100, unique=True)),
                ('hiragana', models.TextField()),
            ],
        ),
    ]
