# Generated by Django 4.2.3 on 2023-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_kanjihiraganaset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WideAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('ad_tag', models.TextField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('click_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'wideads',
            },
        ),
    ]
