# Generated by Django 4.2.3 on 2023-08-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_wideads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='prf_img',
            field=models.ImageField(default='\\media\x07ds_prf_imgs\\広告アイコン.png', upload_to='ads_prf_images'),
        ),
    ]
