# Generated by Django 4.2.3 on 2023-08-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_ads_prf_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='prf_img',
        ),
    ]
