# Generated by Django 4.2.3 on 2023-08-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_ads_prf_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='encoding_done',
            field=models.BooleanField(default=False),
        ),
    ]
