# Generated by Django 4.2.3 on 2023-09-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_recommendeduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='images_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='video_length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
