# Generated by Django 4.2.3 on 2023-09-11 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0027_rename_images_count_posts_content_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='qp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='viewdurations',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_post', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='viewdurations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
