# Generated by Django 4.2.3 on 2023-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_posts_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='is_active',
            new_name='is_real',
        ),
    ]
