# Generated by Django 4.2.3 on 2023-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_rename_is_active_posts_is_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='viewed_by',
        ),
        migrations.AlterField(
            model_name='posts',
            name='hashtag1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hashtag2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hashtag3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
    ]
