# Generated by Django 4.2.3 on 2023-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_remove_posts_viewed_by_alter_posts_hashtag1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
