# Generated by Django 4.2.3 on 2023-09-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_posts_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='qp',
        ),
    ]
