# Generated by Django 4.2.3 on 2023-09-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_remove_posts_qp'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='qp',
            field=models.FloatField(default=1.0),
        ),
    ]
