# Generated by Django 4.2.3 on 2023-09-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_alter_posts_caption'),
        ('posts', '0034_posts_qp'),
    ]

    operations = [
    ]
