# Generated by Django 4.2.3 on 2023-09-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_remove_posts_is_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='TomsTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='others/初期プロフ.jpg', upload_to='tomstalk_images/')),
                ('name', models.CharField(default='トム', max_length=25)),
                ('caption', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True, null=True)),
                ('display_rate', models.IntegerField(default=1)),
            ],
        ),
    ]
