# Generated by Django 4.2.3 on 2023-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_tomstalk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomstalk',
            name='image',
            field=models.ImageField(default='others/初期プロフ.jpg', upload_to='tomstalk/'),
        ),
    ]
