# Generated by Django 4.2.3 on 2023-09-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_alter_tomstalk_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomstalk',
            old_name='caption',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='tomstalk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tomstalk'),
        ),
    ]
