# Generated by Django 4.2.3 on 2023-09-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_posts_emote1_count_posts_emote2_count_and_more'),
        ('posts', '0040_tomstalk_status'),
    ]

    operations = [
    ]
