# Generated by Django 4.2.3 on 2023-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_posts_affiliate_url_alter_posts_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='affiliate_url',
        ),
        migrations.AddField(
            model_name='posts',
            name='affiliate_tag',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
