# Generated by Django 4.2.3 on 2023-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_remove_posts_affiliate_url_posts_affiliate_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='affiliate_tag',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
