# Generated by Django 4.2.3 on 2023-09-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_alter_posts_affiliate_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='emote_total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
