# Generated by Django 4.2.3 on 2023-09-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_posts_is_by_affiliateadvertiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_by_affiliateadvertiser',
        ),
    ]
