# Generated by Django 4.2.3 on 2023-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_remove_posts_is_by_affiliateadvertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='avg_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
