# Generated by Django 4.2.3 on 2023-09-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_posts_avg_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='qp',
        ),
    ]
