# Generated by Django 4.2.3 on 2023-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_remove_posts_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
