# Generated by Django 4.2.3 on 2023-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_posts_views_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewdurations',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='viewdurations',
            name='dummy_field',
            field=models.CharField(default='dummy', max_length=120),
        ),
        migrations.RemoveField(
            model_name='viewdurations',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='viewdurations',
            name='post',
        ),
        migrations.RemoveField(
            model_name='viewdurations',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewdurations',
            name='viewed_at',
        ),
    ]
