# Generated by Django 4.2.3 on 2023-09-28 10:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0053_alter_viewdurations_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewdurations',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viewdurations',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_post', to='posts.posts'),
        ),
        migrations.AddField(
            model_name='viewdurations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewdurations',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='viewdurations',
            unique_together={('user', 'post', 'viewed_at')},
        ),
        migrations.RemoveField(
            model_name='viewdurations',
            name='dummy_field',
        ),
    ]
