# Generated by Django 4.2.3 on 2023-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_viewdurations_duration_viewdurations_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='support_favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
