# Generated by Django 4.2.3 on 2023-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_posts_support_follow_count_posts_support_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='support_views_count',
            field=models.FloatField(default=0),
        ),
    ]
