# Generated by Django 4.2.3 on 2023-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_alter_posts_support_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='support_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
