# Generated by Django 4.2.3 on 2023-10-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_alter_posts_support_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='support_follow_count',
        ),
    ]
