# Generated by Django 4.2.3 on 2023-10-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0063_alter_collection_name_alter_collect_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='scheduled_post_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
