# Generated by Django 4.2.3 on 2023-10-22 11:59

from django.db import migrations, models
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0066_pinnedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinnedpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pinnedpost',
            name='order',
        ),
        migrations.AddField(
            model_name='pinnedpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to=posts.models.adjust_video_pass),
        ),
    ]
