# Generated by Django 4.2.3 on 2023-10-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0067_alter_pinnedpost_options_remove_pinnedpost_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='dash_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='hls_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
