# Generated by Django 4.2.3 on 2023-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0068_videos_dash_path_videos_hls_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='cmaf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
