# Generated by Django 4.2.3 on 2023-10-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0069_videos_cmaf_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='cmaf_path',
        ),
    ]
