# Generated by Django 4.2.3 on 2023-11-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0071_event_eventparticipation_eventparticipationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
