# Generated by Django 4.2.3 on 2023-11-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0072_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
