# Generated by Django 4.2.3 on 2023-11-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FantiaInquiry',
            new_name='NormalInquiry',
        ),
    ]
