# Generated by Django 4.2.3 on 2023-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_corporateinquiry_normalinquiry_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateinquiry',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='メールアドレス'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporateinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('normal', 'Viewyについて'), ('corporate', '法人様からのお問い合わせ')], default='', max_length=100, verbose_name='お問い合わせ種類'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporateinquiry',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='氏名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normalinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('normal', 'Viewyについて'), ('corporate', '法人様からのお問い合わせ')], max_length=100, verbose_name='お問い合わせ種類'),
        ),
    ]
