# Generated by Django 4.2.3 on 2023-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_corporateinquiry_email_corporateinquiry_inquiry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('normal', 'Viewyに関して'), ('corporate', '法人様からのお問い合わせ')], max_length=100, verbose_name='お問い合わせ種類'),
        ),
        migrations.AlterField(
            model_name='normalinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('normal', 'Viewyに関して'), ('corporate', '法人様からのお問い合わせ')], max_length=100, verbose_name='お問い合わせ種類'),
        ),
    ]
