# Generated by Django 4.2.3 on 2023-09-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_users_features'),
        ('posts', '0041_merge_20230914_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orfeatures', models.ManyToManyField(to='accounts.features')),
            ],
        ),
        migrations.CreateModel(
            name='AdInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andfeatures', models.ManyToManyField(to='advertisement.andfeatures')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
    ]
