# Generated by Django 4.2.3 on 2023-09-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_merge_20230914_1039'),
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdInfo',
            new_name='AdInfos',
        ),
    ]
