# Generated by Django 4.2.3 on 2023-09-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_adcampaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinfos',
            name='ad_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_infos', to='advertisement.adcampaigns'),
        ),
    ]
