# Generated by Django 4.2.3 on 2023-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_adcampaigns_total_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinfos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
