# Generated by Django 4.2.3 on 2023-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_adcampaigns_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adinfos',
            name='andfeatures',
        ),
        migrations.AddField(
            model_name='adcampaigns',
            name='andfeatures',
            field=models.ManyToManyField(to='advertisement.andfeatures'),
        ),
    ]
