# Generated by Django 4.2.3 on 2023-09-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_remove_adinfos_andfeatures_adcampaigns_andfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaigns',
            name='andfeatures',
            field=models.ManyToManyField(blank=True, to='advertisement.andfeatures'),
        ),
    ]
