# Generated by Django 4.2.3 on 2023-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_alter_adcampaigns_andfeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaigns',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adinfos',
            name='is_active',
        ),
        migrations.AddField(
            model_name='adcampaigns',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
