# Generated by Django 4.2.3 on 2023-09-24 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_alter_adcampaigns_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaigns',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='adcampaigns',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
