# Generated by Django 4.2.3 on 2023-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_andfeatures_is_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinfos',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
