# Generated by Django 4.2.3 on 2023-09-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0017_requestdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('zoom', 'Zoom'), ('email', 'Email'), ('chat', 'Chat')], max_length=5)),
                ('date_time_1', models.DateTimeField(blank=True, null=True)),
                ('date_time_2', models.DateTimeField(blank=True, null=True)),
                ('date_time_3', models.DateTimeField(blank=True, null=True)),
                ('date_time_4', models.DateTimeField(blank=True, null=True)),
                ('date_time_5', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('x_account', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
