# Generated by Django 4.2.3 on 2023-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0020_monthlyadcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaigns',
            name='target_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
