# Generated by Django 4.2.3 on 2023-10-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0022_alter_monthlyadcost_cpc_alter_monthlyadcost_cpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaigns',
            name='actual_cpc_or_cpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaigns',
            name='pricing_model',
            field=models.CharField(choices=[('CPC', 'CPC'), ('CPM', 'CPM')], default='CPC', max_length=3),
        ),
    ]
