# Generated by Django 4.2.3 on 2023-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0024_adcampaigns_fee_alter_adcampaigns_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinfos',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
