# Generated by Django 4.2.3 on 2023-10-29 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0026_alter_adcampaigns_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaigns',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
