# Generated by Django 4.2.3 on 2023-10-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0029_adcampaigns_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaigns',
            name='monthly_ad_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.monthlyadcost'),
        ),
    ]
