# Generated by Django 4.2.3 on 2023-10-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0030_adcampaigns_monthly_ad_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaigns',
            name='actual_cpc_or_cpm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
