# Generated by Django 4.2.3 on 2023-10-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0031_alter_adcampaigns_actual_cpc_or_cpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaigns',
            name='total_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MonthlyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_views', models.PositiveIntegerField(default=0)),
                ('monthly_clicks', models.PositiveIntegerField(default=0)),
                ('ad_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_billings', to='advertisement.adcampaigns')),
            ],
            options={
                'unique_together': {('ad_campaign', 'month_year')},
            },
        ),
    ]
