# Generated by Django 4.2.3 on 2023-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0032_adcampaigns_total_clicks_count_monthlybilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaigns',
            name='target_clicks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adcampaigns',
            name='target_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
