# Generated by Django 4.2.3 on 2023-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0035_usermonthlybillingsummary_total_fee_with_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinfos',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
