# Generated by Django 4.2.3 on 2023-11-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0036_adinfos_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adinfos',
            name='approved',
        ),
        migrations.AddField(
            model_name='adinfos',
            name='status',
            field=models.CharField(choices=[('pending', '審査中'), ('failed', '審査失敗'), ('approved', '承認済み')], default='pending', max_length=10),
        ),
    ]
