# Generated by Django 4.2.3 on 2023-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0037_remove_adinfos_approved_adinfos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaigns',
            name='fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
