# Generated by Django 4.2.3 on 2023-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0038_alter_adcampaigns_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaigns',
            name='first_time',
            field=models.BooleanField(default=False),
        ),
    ]
