# Generated by Django 4.2.3 on 2023-08-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUserStats',
            new_name='UserStats',
        ),
        migrations.RenameField(
            model_name='userstats',
            old_name='new_users',
            new_name='total_users',
        ),
    ]
