# Generated by Django 4.2.3 on 2023-08-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_newuserstats_userstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
