# Generated by Django 4.2.3 on 2023-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_clickcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
