# Generated by Django 4.2.3 on 2023-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_supportvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportvariable',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
