# Generated by Django 4.2.3 on 2023-10-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_supportvariable_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportVariable',
            new_name='SupportRate',
        ),
    ]
