# Generated by Django 4.2.3 on 2023-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_supportvariable_supportrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrate',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
