# Generated by Django 4.2.3 on 2023-10-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_supportrate_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('repeat_users', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
